name: Run Script on Label

on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]

jobs:
  stay-hello:
    if: github.event.label.name == 'run-script'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run script
        run: echo "Hello, world!"
        